# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionableFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionable_fact', models.CharField(max_length=100)),
                ('user_question', models.CharField(max_length=500)),
                ('questionable_fact_url', models.CharField(max_length=200)),
                ('user_email', models.CharField(max_length=100)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
